import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import Post from "@/components/Post";
import { NavigationBar, NavigationList } from "@/styles/component-styles";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props: any) {
  const postsHolder = [...props.posts.posts];
  console.log(postsHolder);
  const postItems = postsHolder.map((post) => (
    <Post
      id={post.id}
      title={post.title}
      content={post.content}
      author={post.author}
      date={post.date}
    />
  ));
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <NavigationBar>
          <NavigationList>
            <li><Link href="/about">About Us</Link></li>
            <li><Link href="/contact">Contact Us</Link></li>
            <li><Link href="/careers">Careers</Link></li>
            <li><Link href="/products">Products</Link></li>
          </NavigationList>
        </NavigationBar>
        {postItems}
      </>
    </>
  );
}

export const getServerSideProps = async () => {
  const postsResponse = await fetch("http://localhost:3000/posts");
  const posts = await postsResponse.json();
  console.log("posts are ", posts);

  return {
    props: { posts: { posts } },
  };
};
